jknet
BUPT-GAMMA/GammaGL pull request #11
Opened 2022-04-18 03:52 UTC by jymmmmm

添加了jknet相关代码，包括jknet_trainer.py, jknet.py, JumpingKnowledge.py

2022-04-26 07:25 UTC, clearhanhui requested changes

2022-04-26 07:25 UTC, clearhanhui commented on examples/jknet/jknet_trainer.py
> +from gammagl.models import JKNet,GCNModel, APPNPModel
为什么导入appnp。没有用到的import尽量都删掉
最新的calc norm函数改到utils里里面了，这里改一下

2022-04-26 07:25 UTC, clearhanhui commented on gammagl/layers/pool/__init__.py
> +from .JumpingKnowledge import JumpingKnowledge
把模型写在layers/conv下面

2022-04-26 07:25 UTC, clearhanhui commented on examples/jknet/jknet_trainer.py
> +    optimizer = tlx.optimizers.Adam(learning_rate=args.lr, weight_decay=args.weight_decay)
tlx最新的api是参数名是lr，更新gammagl和tlx最新的代码跑一下，有bug反馈一下

2022-04-26 07:25 UTC, clearhanhui commented on gammagl/layers/pool/JumpingKnowledge.py
> +# -*- coding: utf-8 -*-
trainer文件下面添加一个readme.md文件，把模型相关的内容写一下，论文、公式、实验结果

2022-04-29 08:22 UTC, Theheavens commented on gammagl/models/jknet.py
> +        layer_out = []  # 保存每一层的结果
不要出现中文

2022-05-05 11:55 UTC, clearhanhui commented on examples/jknet/readme.md
> +| Dataset | mode | Accuracy | std | Params |
params和mode这一栏去掉吧

2022-05-05 11:58 UTC, clearhanhui commented on examples/jknet/readme.md
> +| Dataset | mode | Accuracy | std | Params |
把作者的性能也写上，然后把mode和params这两列删掉

2022-05-09 05:44 UTC, merged