Luoxc
BUPT-GAMMA/GammaGL pull request #110
Opened 2022-11-29 13:21 UTC by LuoXC-Wu

## Changes
add VGAE Model.

2022-12-14 08:16 UTC, Theheavens requested changes

2022-12-14 08:16 UTC, Theheavens commented on gammagl/models/__init__.py
> +>>>>>>> main
？

2022-12-14 08:16 UTC, Theheavens commented on examples/vgae/readme.md
> +```bash
VGAE和GAE拆成两个部分吧

2022-12-14 08:16 UTC, Theheavens commented on gammagl/transforms/random_link_split.py
> +def mask_test_edges(adj):
这几个函数为什么在这个文件里？
https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/transforms/random_link_split.py

2022-12-14 09:08 UTC, clingingsai commented on gammagl/transforms/random_link_split.py
> +def mask_test_edges(adj):
参考pyG，对链接预测任务的预处理函数放在这个文件里

2022-12-19 09:28 UTC, merged

2022-12-19 09:56 UTC, Theheavens commented
TODO: update `vgae_pre` with `random_link_split`.